<!-- 燈箱：登入 -->
<div id="lightBox" style="display:none">
<table border="1" align="center" cellspacing="0" id="tableLogin">
<tr><td>帳號</td><td><input type="text" name="memId" id="memId"></td></tr>
<tr><td>密碼</td><td><input type="password" name="memPsw" id="memPsw"></td></tr>
<tr><td colspan="2" align="center">
        <input type="button" id="btnLogin" value="登入">
        <input type="button" id="btnLoginCancel" value="取消">
    </td></tr>
</table>
</div>

<!-- <img src="大頭照.jpg">-->
<div id="bar" style="position: absolute;top:0;right: 20px">
<span id="memName">&nbsp;</span>   <!-- 使用者姓名 -->
<span id="spanLogin">登入</span>
</div>